### ISSUE TITLE
Prepare Unit Tests for mm1 and mm1k  functions in queuing theory.py

### ISSUE THREAD

**Issue by Antonio-Tresol** [Antonio-Tresol/ORLib#1]
Use pytest. Use AAA testing format. Examples to test can found in Hillier and Lieberman ed.11 chapter 17. Remember to use equivalence partitioning to test.

**Comment by JirlOP** [comment]
## MM1 unit tests prepared.
Prove images:

![Image](https://github.com/Operations-Research-lib/ORLib/assets/86182192/d1cc4412-87e6-46ba-8471-959374e11910)

### Last commit
adece57

### Compare with main
[See compare version of item/ORlib1 with main branch](https://github.com/Operations-Research-lib/ORLib/compare/main...item/ORlib-1)

@Antonio-Tresol @GoninDS

**Comment by JirlOP** [comment]
# MM1K unit test prepared
## Prove images
![Image](https://github.com/Operations-Research-lib/ORLib/assets/86182192/e68e46b9-ceb0-431f-bb56-8f61190c5a26)


## item/ORLib last Commit 
7f79d61

## item/ORLib  merge into develop
fc4a86a
